---
- name: Set up MySQL on Database Server
  hosts: dbservers
  become: yes
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL to bind to all interfaces
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: restart mysql

    - name: Install PyMySQL (Python MySQL module)
      apt:
        name: python3-pymysql
        state: present

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted

